version: '3'
services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_URL=http://goapp:8080
    depends_on:
      - goapp

  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgres://plec:example@db:5432/business?sslmode=disable'
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_DB: business
      POSTGRES_USER: 'plec'
      POSTGRES_PASSWORD: example
      
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
